// 定义状态排序逻辑
export const statusOrder = { 'Enabled': 1, 'Draft': 2, 'Disabled': 3, 'Deprecated': 4 };

// 模拟 Workout 数据

export const listData = [
    {
        id: 1,
        type: 'video',
        imageCoverUrl:"https://2d.zol-img.com.cn/product/270_160x120/525/cejVQOyTTMea2.png",
        name:"123",
        status:0,
        met:"1",
        structureType:"asd",
        difficulty:"asd",
        equipment:"asd",
        position:"asd",
        target:"asd",
        frontVideoStatus:"Successful",
        sideVideoStatus:"Processing"
    },
    {
        id: 2,
        type: 'video',
        imageCoverUrl:"https://2d.zol-img.com.cn/product/270_160x120/525/cejVQOyTTMea2.png",
        name:"123123",
        status:1,
        met:"1",
        structureType:"asd",
        difficulty:"asd",
        equipment:"asd",
        position:"asd",
        target:"asd",
        frontVideoStatus:"Successful",
        sideVideoStatus:"Processing"
    },
    {
        id: 3,
        type: 'video',
        imageCoverUrl:"https://2d.zol-img.com.cn/product/270_160x120/525/cejVQOyTTMea2.png",
        name:"12312312",
        status:2,
        met:"1",
        structureType:"asd",
        difficulty:"asd",
        equipment:"asd",
        position:"asd",
        target:"asd",
        frontVideoStatus:"Successful",
        sideVideoStatus:"Processing"
    },
    {
        id: 4,
        type: 'video',
        imageCoverUrl:"https://2d.zol-img.com.cn/product/270_160x120/525/cejVQOyTTMea2.png",
        name:"12312312",
        status:2,
        met:"1",
        structureType:"asd",
        difficulty:"asd",
        equipment:"asd",
        position:"asd",
        target:"asd",
        frontVideoStatus:"Successful",
        sideVideoStatus:"Processing"
    },
    // {
    //     id: 5,
    //     type: 'video',
    //     imageCoverUrl:"https://2d.zol-img.com.cn/product/270_160x120/525/cejVQOyTTMea2.png",
    //     name:"12312312",
    //     status:2,
    //     met:"1",
    //     structureType:"asd",
    //     difficulty:"asd",
    //     equipment:"asd",
    //     position:"asd",
    //     target:"asd",
    //     frontVideoStatus:"Successful",
    //     sideVideoStatus:"Processing"
    // },
    // {
    //     id: 6,
    //     type: 'video',
    //     imageCoverUrl:"https://2d.zol-img.com.cn/product/270_160x120/525/cejVQOyTTMea2.png",
    //     name:"12312312",
    //     status:2,
    //     met:"1",
    //     structureType:"asd",
    //     difficulty:"asd",
    //     equipment:"asd",
    //     position:"asd",
    //     target:"asd",
    //     frontVideoStatus:"Successful",
    //     sideVideoStatus:"Processing"
    // },
    // {
    //     id: 7,
    //     type: 'video',
    //     imageCoverUrl:"https://2d.zol-img.com.cn/product/270_160x120/525/cejVQOyTTMea2.png",
    //     name:"12312312",
    //     status:2,
    //     met:"1",
    //     structureType:"asd",
    //     difficulty:"asd",
    //     equipment:"asd",
    //     position:"asd",
    //     target:"asd",
    //     frontVideoStatus:"Successful",
    //     sideVideoStatus:"Processing"
    // },
    // {
    //     id: 8,
    //     type: 'video',
    //     imageCoverUrl:"https://2d.zol-img.com.cn/product/270_160x120/525/cejVQOyTTMea2.png",
    //     name:"12312312",
    //     status:2,
    //     met:"1",
    //     structureType:"asd",
    //     difficulty:"asd",
    //     equipment:"asd",
    //     position:"asd",
    //     target:"asd",
    //     frontVideoStatus:"Successful",
    //     sideVideoStatus:"Processing"
    // },
    // {
    //     id: 9,
    //     type: 'video',
    //     imageCoverUrl:"https://2d.zol-img.com.cn/product/270_160x120/525/cejVQOyTTMea2.png",
    //     name:"12312312",
    //     status:2,
    //     met:"1",
    //     structureType:"asd",
    //     difficulty:"asd",
    //     equipment:"asd",
    //     position:"asd",
    //     target:"asd",
    //     frontVideoStatus:"Successful",
    //     sideVideoStatus:"Processing"
    // },
    // {
    //     id: 11,
    //     type: 'video',
    //     imageCoverUrl:"https://2d.zol-img.com.cn/product/270_160x120/525/cejVQOyTTMea2.png",
    //     name:"12312312",
    //     status:2,
    //     met:"1",
    //     structureType:"asd",
    //     difficulty:"asd",
    //     equipment:"asd",
    //     position:"asd",
    //     target:"asd",
    //     frontVideoStatus:"Successful",
    //     sideVideoStatus:"Processing"
    // },
    // {
    //     id: 12,
    //     type: 'video',
    //     imageCoverUrl:"https://2d.zol-img.com.cn/product/270_160x120/525/cejVQOyTTMea2.png",
    //     name:"12312312",
    //     status:2,
    //     met:"1",
    //     structureType:"asd",
    //     difficulty:"asd",
    //     equipment:"asd",
    //     position:"asd",
    //     target:"asd",
    //     frontVideoStatus:"Successful",
    //     sideVideoStatus:"Processing"
    // },
]

// 定义筛选器配置
export const filterSections = [
    {
        title: 'Status',
        key: 'status',
        options: ['Draft', 'Enabled', 'Disabled', 'Deprecated'],
    },
    {
        title: 'Function Type',
        key: 'functionType',
        options: ['Warm Up', 'Main', 'Cool Down']
    },
    {
        title: 'Difficulty',
        key: 'difficulty',
        options: ['Beginner', 'Intermediate', 'Advanced']
    },
    {
        title: 'Position',
        key: 'position',
        options: ['Standing', 'Lying', 'Seated', 'Prone', 'Kneeling'],
    },
    {
        title: 'Target',
        key: 'target',
        options: ['Full Body', 'Arm', 'Back', 'Butt', 'Abs', 'Leg', 'Core'],
    }
];

// 用于编辑器"结构(Structure)"部分的模拟数据
// 恢复为直接的数组结构
// 添加或填充用于筛选的字段：functionType, difficulty, position, target
export const mockEditorStructureData = [
    {
        "id": 1896,
        "combination": "Normal",
        "exerciseName": "TUCK TO PIKE--Cycling Bike",
        "displayName": "TUCK TO PIKE--Cycling Bike",
        "groupId": "96518862ef744ba78e43365dd244aa11",
        "concatName": "",
        "groupShow": 1,
        "exerciseType": "Fit",
        "exerciseSubType": "Cardio,HIIT",
        "description": "1",
        "videoLinkUrl": "https://youtu.be/g2jocInockU?t=190",
        "animationId": 1529,
        "soundId": 1529,
        "bodyPart": "Upper body",
        "target": "Core",
        "position": "Prone",
        "focus": "Strength",
        "equipment": "Cycling Bike,Dumbbells,Pillow",
        "met": 8,
        "star": null,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2023-09-14 11:09:18",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Advanced",
        "functionType": "Main",
        "intensity": "level 2"
    },
    {
        "id": 1895,
        "combination": "Normal",
        "exerciseName": "V SIT AND LEG SPREAD",
        "displayName": "V SIT AND LEG SPREAD--Kettlebells",
        "groupId": "d33fb722c3794c3e969b627538a612c0",
        "concatName": "",
        "groupShow": 1,
        "exerciseType": "Fit",
        "exerciseSubType": "Cardio,HIIT",
        "description": "1",
        "videoLinkUrl": "https://youtu.be/fY1ESrO2zpc?t=163",
        "animationId": 1530,
        "soundId": 1530,
        "bodyPart": "Lower body",
        "target": "Arm,Butt,Core,Leg",
        "position": "Lying",
        "focus": "Strength",
        "equipment": "Kettlebells",
        "met": 12,
        "star": null,
        "specialNeed": "Knee-friendly,Wrist-friendly",
        "remark": "",
        "status": 'Disabled',
        "createTime": "2023-09-14 11:07:24",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Advanced",
        "functionType": "Main",
        "intensity": "level 3"
    },
    {
        "id": 1894,
        "combination": "Left & Right",
        "exerciseName": "SIDE V SIT UP",
        "displayName": "SIDE V SIT UP",
        "groupId": "247381da31734708b6a0b019ae5bfa63",
        "concatName": "(Right)",
        "groupShow": 0,
        "exerciseType": "Fit",
        "exerciseSubType": "Cardio",
        "description": "2",
        "videoLinkUrl": "https://youtu.be/HGl447ifkU8?t=19",
        "animationId": 993,
        "soundId": 993,
        "bodyPart": "Total body",
        "target": "Butt,Core,Thigh",
        "position": "Prone",
        "focus": "Balancing",
        "equipment": "Cycling Bike,Kettlebells",
        "met": 12,
        "star": null,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2023-09-14 10:51:29",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Intermediate",
        "functionType": "Warm Up",
        "intensity": "level 3"
    },
    {
        "id": 1893,
        "combination": "Left & Right",
        "exerciseName": "SIDE V SIT UP",
        "displayName": "SIDE V SIT UP",
        "groupId": "247381da31734708b6a0b019ae5bfa63",
        "concatName": "(Left)",
        "groupShow": 1,
        "exerciseType": "Fit",
        "exerciseSubType": "Cardio",
        "description": "1",
        "videoLinkUrl": "https://youtu.be/HGl447ifkU8?t=19",
        "animationId": 993,
        "soundId": 993,
        "bodyPart": "Total body",
        "target": "Butt,Core,Thigh",
        "position": "Prone",
        "focus": "Balancing",
        "equipment": "Cycling Bike,Kettlebells",
        "met": 12,
        "star": null,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2023-09-14 10:51:29",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Intermediate",
        "functionType": "Warm Up",
        "intensity": "level 3"
    },
    {
        "id": 1874,
        "combination": "Normal",
        "exerciseName": "FG",
        "displayName": "FG",
        "groupId": "f4af839b64574535ad23de7817795207",
        "concatName": "",
        "groupShow": 1,
        "exerciseType": "Faceyoga",
        "exerciseSubType": "",
        "description": "GF",
        "videoLinkUrl": "FG",
        "animationId": 1865,
        "soundId": 1871,
        "bodyPart": "Face",
        "target": "Face Muscles",
        "position": "Seated",
        "focus": "Relaxation",
        "equipment": "",
        "met": null,
        "star": null,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-12-23 13:38:30",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Cool Down",
        "intensity": ""
    },
    {
        "id": 1872,
        "combination": "Normal",
        "exerciseName": "SUPINE BENT KNEES YOGA",
        "displayName": "SUPINE BENT KNEES",
        "groupId": "703cff27c80d4c08b71dbddea17a6d1a",
        "concatName": "",
        "groupShow": 1,
        "exerciseType": "Yoga",
        "exerciseSubType": "",
        "description": "Lying on a mat with your knees bent and feet flat on the floor. \n\nBreath deep and settle the spine on the floor to quickly bring the breathing back to normal.",
        "videoLinkUrl": "https://youtu.be/VfSlEgg4ApE?t=1447",
        "animationId": 1872,
        "soundId": 1872,
        "bodyPart": "Lower body",
        "target": "Arm",
        "position": "Lying",
        "focus": "Relaxation",
        "equipment": "Yoga mat",
        "met": 3,
        "star": 1,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Cool Down",
        "intensity": "level 1"
    },
    {
        "id": 1871,
        "combination": "Normal",
        "exerciseName": "STAFF BENT KNEES YOGA",
        "displayName": "STAFF BENT KNEES",
        "groupId": "1c4db3154a74476ab612b540f9e8ba6a",
        "concatName": "",
        "groupShow": 1,
        "exerciseType": "Yoga",
        "exerciseSubType": "Ashtanga",
        "description": "Distribute your weight between three points. \n\nFeet flat to the floor, bend in the knees, hands beside your hips.",
        "videoLinkUrl": "https://youtu.be/sXz0OCjO3p4?t=250",
        "animationId": 1871,
        "soundId": 1871,
        "bodyPart": "Upper body",
        "target": "Abs",
        "position": "Seated",
        "focus": "Relaxation",
        "equipment": "Resistance band,Yoga mat",
        "met": 3,
        "star": 1,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Cool Down",
        "intensity": "level 1"
    },
    {
        "id": 1870,
        "combination": "Left & Right",
        "exerciseName": "123456",
        "displayName": "low hunge123--bed",
        "groupId": "691e4ffed881478ca3c25b6caddbe8b2",
        "concatName": "(Left)",
        "groupShow": 1,
        "exerciseType": "Yoga",
        "exerciseSubType": "Ashtanga,Hatha,Pilates,Vinyasa",
        "description": "我是一颗小小的石头，深深的埋在泥土之中",
        "videoLinkUrl": "https://youtu.be/O4xzzKdZy4Q?t=395",
        "animationId": 1870,
        "soundId": 1870,
        "bodyPart": "Lower body",
        "target": "Thigh,Butt,Leg,Hip,Hamstring",
        "position": "Prone",
        "focus": "Flexibility",
        "equipment": "Bed",
        "met": 3,
        "star": 2,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Main",
        "intensity": "level 1"
    },
    {
        "id": 1869,
        "combination": "Left & Right",
        "exerciseName": "123456",
        "displayName": "low hunge123--bed",
        "groupId": "691e4ffed881478ca3c25b6caddbe8b2",
        "concatName": "(Right)",
        "groupShow": 0,
        "exerciseType": "Yoga",
        "exerciseSubType": "Ashtanga,Hatha,Pilates,Vinyasa",
        "description": "我是一颗小小的石头，深深的埋在泥土之中",
        "videoLinkUrl": "https://youtu.be/O4xzzKdZy4Q?t=395",
        "animationId": 1869,
        "soundId": 1869,
        "bodyPart": "Lower body",
        "target": "Thigh,Butt,Leg,Hip,Hamstring",
        "position": "Prone",
        "focus": "Flexibility",
        "equipment": "Bed",
        "met": 3,
        "star": 2,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Main",
        "intensity": "level 1"
    },
    {
        "id": 1868,
        "combination": "Left & Right",
        "exerciseName": "奥力给就看到家里发大水654",
        "displayName": "HIGH LUNGE123456--chair",
        "groupId": "cda85a67b03e41af8b2ebd774a84fe4f",
        "concatName": "(Left)",
        "groupShow": 1,
        "exerciseType": "Yoga",
        "exerciseSubType": "Hatha,Pilates,Restorative",
        "description": "11111111111",
        "videoLinkUrl": "https://youtu.be/O4xzzKdZy4Q?t=409",
        "animationId": 1868,
        "soundId": 1868,
        "bodyPart": "Total body",
        "target": "Thigh,Butt,Leg,Back,Shoulder,Chest,Arm,Hip,Spine,Lower back",
        "position": "Standing",
        "focus": "Flexibility",
        "equipment": "Chair",
        "met": 3,
        "star": 2,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Main",
        "intensity": "level 1"
    }
];

export const mockUsers = [
    {
        id: 1,
        name: 'John Smith',
        email: 'john.smith@example.com',
        avatar: 'internal/test/268a8e7dd3ea45268a96588f0f07e4f8.png',
        createUser: 'Admin',
        createTime: '2024-01-15 10:00:00',
        status: 2, // 'enable' -> 1
        status1: 1,
        birthday: '1990-01-15',
        startDate: '2024-05-01',
        endDate: '2024-12-31'
    },
    {
        id: 2,
        name: 'Emma Wilson',
        email: 'emma.wilson@example.com',
        avatar: '',  // 空头像测试
        createUser: 'Admin',
        createTime: '2024-01-16 14:30:00',
        status: 1, // 'enable' -> 1
        birthday: '1992-03-22',
        startDate: '2024-06-15',
        endDate: '2025-06-14'
    },
    {
        id: 3,
        name: 'Michael Brown',
        email: 'michael.brown@example.com',
        avatar: null,  // 空头像测试
        createUser: 'Manager',
        createTime: '2024-01-17 09:15:00',
        status: 0, // 'disable' -> 0
        birthday: '1985-11-08',
        startDate: '2024-01-01',
        endDate: '2024-12-31'
    },
    {
        id: 4,
        name: 'Sarah Davis',
        displayImage: 'internal/test/268a8e7dd3ea45268a96588f0f07e4f8.png',
        email: 'sarah.davis@example.com',
        avatar: 'internal/test/268a8e7dd3ea45268a96588f0f07e4f8.png',
        createUser: 'Manager',
        createTime: '2024-02-18 16:45:00',
        birthday: "2001-05-13",
        status: 1,
        status1: 'Enabled1',
        status221: 1,
        status2: [1, 2],
        startDate: '2024-07-25',
        endDate: '2025-09-25',
        contentStyle: 'style2',
        layoutType: 2,
        layoutTypeText: 'saasdadas',
        soundScript: 'soundScript饿饿饿饿',
        name23: 'textareaxx soundScript饿饿饿饿 soundScript饿饿饿饿 s  soundScript饿饿饿饿soundScript饿饿饿饿soundScript饿饿饿饿soundScript饿饿饿饿 oundScript饿饿饿饿 soundScript饿饿饿饿 xxx',
        warmNumber: 30,
        warmCycles: 4,
        warmName: 'warmName',
        userPassword: '1sdf23456',
    }
];