
export const listData = [
    {
        id: 1,
        version: '1.0.0',
        comment:"この王の力、神羅てんせい！！！",
        user:"王の力",
        time:"200s",
        result:1,
        failReason:null,
    },
    {
        id: 2,
        version: '1.0.0',
        comment:"この王の力、神羅てんせい！！！",
        user:"王の力",
        time:"200s",
        result:2,
        failReason:null,
    },
    {
        id: 3,
        version: '1.0.0',
        comment:"この王の力、神羅てんせい！！！",
        user:"王の力",
        time:"200s",
        result:"success",
        failReason:null,
    },
    {
        id: 4,
        version: '1.0.0',
        comment:"この王の力、神羅てんせい！！！",
        user:"王の力",
        time:"200s",
        result:"success",
        failReason:null,
    },
    {
        id: 5,
        version: '1.0.0',
        comment:"この王の力、神羅てんせい！！！",
        user:"王の力",
        time:"200s",
        result:"success",
        failReason:null,
    },
    {
        id: 6,
        version: '1.0.0',
        comment:"この王の力、神羅てんせい！！！",
        user:"王の力",
        time:"200s",
        result:"success",
        failReason:null,
    },
    {
        id: 7,
        version: '1.0.0',
        comment:"この王の力、神羅てんせい！！！",
        user:"王の力",
        time:"200s",
        result:"success",
        failReason:null,
    },
    {
        id: 8,
        version: '1.0.0',
        comment:"この王の力、神羅てんせい！！！",
        user:"王の力",
        time:"200s",
        result:"success",
        failReason:null,
    },
    {
        id: 9,
        version: '1.0.0',
        comment:"この王の力、神羅てんせい！！！",
        user:"王の力",
        time:"200s",
        result:"success",
        failReason:null,
    },
]