// 定义状态排序权重
export const statusOrder = { 'Enabled': 1, 'Draft': 2, 'Disabled': 3, 'Deprecated': 4 };

// 定义难度排序权重
export const difficultyOrder = { 'Easy': 1, 'Medium': 2, 'Hard': 3 };

// 定义 localStorage 中存储可见列信息的 Key
export const WORKOUT_LIST_VISIBLE_COLUMNS_KEY = 'workoutListVisibleColumns';


// 默认可见表格列的 Key
export const DEFAULT_VISIBLE_TABLE_COLUMN_KEYS = [
    'subscription',
    'duration',
    'calorie'
];

// 所有额外的 Workout 列表表格列 Key (用于列选择器)
export const ALL_TABLE_COLUMN_KEYS = [
    'detailImage',      // 详情页图片
    'thumbnailImage',   // 缩略图
    'completeImage',    // 完成页图片
    'difficulty',       // 难度
    'equipment',        // 器材
    'position',         // 体位
    'target',           // 目标部位
    'exerciseNum',      // Exercise 数量
    'newDate',          // 新的合并日期列
    'audioLang',        // 音频语言
    'fileStatus',       // 文件状态
];

// 定义 器材(Equipment) 选项 (用于编辑器和筛选器)
export const equipmentOptions = ['Dumbbell', 'Resistance band', 'None'];

// 定义筛选器配置 (筛选模式在具体组件使用时指定)
export const filterSections = [
    {
        title: 'Status',
        key: 'status',
        options: ['Draft', 'Enabled', 'Disabled', 'Deprecated'],
    },
    {
        title: 'Difficulty',
        key: 'difficulty',
        options: ['Beginner', 'Intermediate', 'Advanced'],
    },
    {
        title: 'Equipment',
        key: 'equipment',
        options: ['Dumbbells', 'Resistance band', 'None'],
    },
    // {
    //     title: 'Function Type',
    //     key: 'functionType',
    //     options: ['Warm Up', 'Main', 'Cool Down'],
    // },

    {
        title: 'Position',
        key: 'position',
        options: ['Standing', 'Lying', 'Seated', 'Prone', 'Kneeling'],
    },
    {
        title: 'Target',
        key: 'target',
        options: ['Full Body', 'Arm', 'Back', 'Butt', 'Abs', 'Leg', 'Core'],
    }
];

// --- 以下是从 WorkoutsEditor.jsx 移动并整理的数据 ---

// 模拟 Workout 列表数据 (保持原名 mockWorkoutsForList，以防列表页直接使用)
export const mockWorkoutsForList = [
    {
        id: 1,
        type: 'video',
        image: 'https://hhcontent.s3.eu-central-1.amazonaws.com/t/none/u/undefined/w/67f5dfa1916d1900124391ea/x/video_720p.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIA4KU4XQXHZETDYO3V%2F20250415%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20250415T085513Z&X-Amz-Expires=604800&X-Amz-Signature=5aaf8d86a1deccfda9931d29ab10753adc3aaba5e0b4588015aac99a2640cd58&X-Amz-SignedHeaders=host&x-amz-request-payer=requester&x-id=GetObject', // 列表/编辑器封面图
        name: 'Morning RunMorning RunMorning RunMorning RunMorning RunMorning RunMorning Run',
        status: 'Enabled',
        difficulty: 'Medium',
        equipment: 'Running Shoes',
        position: 'Standing', // 使用字符串而非数字
        target: 'Cardio',
        newDate: '2025-01-26 06:00:00',
        category: 'Cardio', // Workout 分类
        duration: 185, // 时长 (秒)
        calorie: 150, // 卡路里 (kcal)
        isSubscription: false, // 是否为 Premium 内容
        detailImage: 'https://via.placeholder.com/800x600.png?text=Detail+Image+1', // 详情页图片
        thumbnailImage: 'https://via.placeholder.com/150.png?text=Thumb+1', // 缩略图
        completeImage: 'https://via.placeholder.com/400x300.png?text=Complete+1', // 完成页图片
        exerciseNum: 8, // 包含的 Exercise 数量
        audioLang: 'en-US', // 音频语言
        fileStatus: ['Successful', 'Processing', 'Failed'][Math.floor(Math.random() * 3)], // 文件状态 (例如视频/音频文件)
    },
    {
        id: 2,
        type: 'image',
        image: 'https://amber.7mfitness.com/cms/fitnessVideo/img/6379cf54631c41469b5fedb0900bbb42.png?alt=media&name=f3683cc7-f759-4ed2-a9f3-4f1d10123c6d.png',
        name: 'Weight Lifting',
        status: 'Disabled',
        difficulty: 'Hard',
        equipment: 'Dumbbells, Barbell',
        position: 'Standing',
        target: 'Strength',
        newDate: '2025-02-27 18:00:00',
        category: 'Strength',
        duration: 3600,
        calorie: 450,
        isSubscription: false,
        detailImage: null,
        thumbnailImage: 'https://via.placeholder.com/150.png?text=Thumb+2',
        completeImage: null,
        exerciseNum: 12,
        audioLang: null,
        fileStatus: ['Successful', 'Processing', 'Failed'][Math.floor(Math.random() * 3)],
    },
    {
        id: 3,
        type: 'image',
        image: 'https://amber.7mfitness.com/cms/fitnessVideo/img/6379cf54631c41469b5fedb0900bbb42.png?alt=media&name=f3683cc7-f759-4ed2-a9f3-4f1d10123c6d.png',
        name: 'Yoga Session',
        status: 'Enabled',
        difficulty: 'Easy',
        equipment: 'Yoga Mat',
        position: 'Lying',
        target: 'Flexibility',
        newDate: '2025-07-28 08:00:00',
        category: 'Yoga',
        duration: 2700,
        calorie: 200,
        isSubscription: true, // 示例 Premium 内容
        detailImage: 'https://via.placeholder.com/800x600.png?text=Detail+Image+3',
        thumbnailImage: 'https://via.placeholder.com/150.png?text=Thumb+3',
        completeImage: 'https://via.placeholder.com/400x300.png?text=Complete+3',
        exerciseNum: 15,
        audioLang: 'en-US',
        fileStatus: ['Successful', 'Processing', 'Failed'][Math.floor(Math.random() * 3)],
    },
    {
        id: 44,
        type: 'image',
        image: null,
        name: 'Cycling',
        status: 'Draft',
        difficulty: 'Medium',
        equipment: 'Bicycle, Helmet',
        position: 'Seated',
        target: 'Cardio, Endurance',
        newDate: '2025-07-29 17:00:00',
        category: 'Cardio',
        duration: 5400,
        calorie: 600,
        isSubscription: false,
        detailImage: null,
        thumbnailImage: null,
        completeImage: null,
        exerciseNum: 1, // 可能只有一个主要动作
        audioLang: 'zh-CN',
        fileStatus: ['Successful', 'Processing', 'Failed'][Math.floor(Math.random() * 3)], // 草稿状态也可能有文件状态
    },
    {
        id: 5,
        type: 'image',
        image: 'https://amber.7mfitness.com/cms/fitnessVideo/img/6379cf54631c41469b5fedb0900bbb42.png?alt=media&name=f3683cc7-f759-4ed2-a9f3-4f1d10123c6d.png',
        name: 'HIIT Workout',
        status: 'Deprecated',
        difficulty: 'Hard',
        equipment: 'None',
        position: 'Standing',
        target: 'Fat Loss, Fitness',
        newDate: '2025-07-30 12:00:00',
        category: 'HIIT',
        duration: 1800,
        calorie: 350,
        isSubscription: false,
        detailImage: 'https://via.placeholder.com/800x600.png?text=Detail+Image+5',
        thumbnailImage: 'https://via.placeholder.com/150.png?text=Thumb+5',
        completeImage: 'https://via.placeholder.com/400x300.png?text=Complete+5',
        exerciseNum: 10,
        audioLang: 'en-US',
        fileStatus: ['Successful', 'Processing', 'Failed'][Math.floor(Math.random() * 3)], // 示例错误状态
    },
];


// 新 Workout 的初始数据结构
export const initialWorkoutData = {
    id: null,
    name: '',
    status: 'Draft', // 新 Workout 的默认状态
    difficulty: 'Medium',
    equipment: '',
    position: null,
    target: '',
    image: null, // Workout 的封面图，与结构(Structure)中的 Exercise 图片不同
    newDate: null,
    structure: [], // 结构数组，初始为空
    videoPreferences: {}, // 视频偏好设置，初始为空对象
    musicLinks: [], // 音乐链接数组，初始为空
};

// 用于编辑器"结构(Structure)"部分的模拟 Exercise 数据
// 注意：此数据也可能用于内容库 (Content Library)
export const mockEditorStructureData = [
    {
        "id": 1896,
        "combination": "Normal",
        "exerciseName": "TUCK TO PIKE--Cycling Bike",
        "displayName": "TUCK TO PIKE--Cycling Bike",
        "groupId": "96518862ef744ba78e43365dd244aa11",
        "concatName": "",
        "groupShow": 1,
        "exerciseType": "Fit",
        "exerciseSubType": "Cardio,HIIT",
        "description": "1",
        "videoLinkUrl": "https://youtu.be/g2jocInockU?t=190",
        "animationId": 1529,
        "soundId": 1529,
        "bodyPart": "Upper body",
        "target": "Core",
        "position": "Prone",
        "focus": "Strength",
        "equipment": "Cycling Bike,Dumbbells,Pillow",
        "met": 8,
        "star": null,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2023-09-14 11:09:18",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Advanced",
        "functionType": "Main",
        "intensity": "level 2",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1895,
        "combination": "Normal",
        "exerciseName": "V SIT AND LEG SPREAD",
        "displayName": "V SIT AND LEG SPREAD--Kettlebells",
        "groupId": "d33fb722c3794c3e969b627538a612c0",
        "concatName": "",
        "groupShow": 1,
        "exerciseType": "Fit",
        "exerciseSubType": "Cardio,HIIT",
        "description": "1",
        "videoLinkUrl": "https://youtu.be/fY1ESrO2zpc?t=163",
        "animationId": 1530,
        "soundId": 1530,
        "bodyPart": "Lower body",
        "target": "Arm,Butt,Core,Leg",
        "position": "Lying",
        "focus": "Strength",
        "equipment": "Kettlebells",
        "met": 12,
        "star": null,
        "specialNeed": "Knee-friendly,Wrist-friendly",
        "remark": "",
        "status": 'Disabled',
        "createTime": "2023-09-14 11:07:24",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Advanced",
        "functionType": "Main",
        "intensity": "level 3",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1894,
        "combination": "Left & Right",
        "exerciseName": "SIDE V SIT UP",
        "displayName": "SIDE V SIT UP",
        "groupId": "247381da31734708b6a0b019ae5bfa63",
        "concatName": "(Right)",
        "groupShow": 0,
        "exerciseType": "Fit",
        "exerciseSubType": "Cardio",
        "description": "2",
        "videoLinkUrl": "https://youtu.be/HGl447ifkU8?t=19",
        "animationId": 993,
        "soundId": 993,
        "bodyPart": "Total body",
        "target": "Butt,Core,Thigh",
        "position": "Prone",
        "focus": "Balancing",
        "equipment": "Cycling Bike,Kettlebells",
        "met": 12,
        "star": null,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2023-09-14 10:51:29",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Intermediate",
        "functionType": "Warm Up",
        "intensity": "level 3",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1893,
        "combination": "Left & Right",
        "exerciseName": "SIDE V SIT UP",
        "displayName": "SIDE V SIT UP",
        "groupId": "247381da31734708b6a0b019ae5bfa63",
        "concatName": "(Left)",
        "groupShow": 1,
        "exerciseType": "Fit",
        "exerciseSubType": "Cardio",
        "description": "1",
        "videoLinkUrl": "https://youtu.be/HGl447ifkU8?t=19",
        "animationId": 993,
        "soundId": 993,
        "bodyPart": "Total body",
        "target": "Butt,Core,Thigh",
        "position": "Prone",
        "focus": "Balancing",
        "equipment": "Cycling Bike,Kettlebells",
        "met": 12,
        "star": null,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2023-09-14 10:51:29",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Intermediate",
        "functionType": "Warm Up",
        "intensity": "level 3",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1874,
        "combination": "Normal",
        "exerciseName": "FG",
        "displayName": "FG",
        "groupId": "f4af839b64574535ad23de7817795207",
        "concatName": "",
        "groupShow": 1,
        "exerciseType": "Faceyoga",
        "exerciseSubType": "",
        "description": "GF",
        "videoLinkUrl": "FG",
        "animationId": 1865,
        "soundId": 1871,
        "bodyPart": "Face",
        "target": "Face Muscles",
        "position": "Seated",
        "focus": "Relaxation",
        "equipment": "",
        "met": 2.0,
        "star": null,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-12-23 13:38:30",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Cool Down",
        "intensity": "",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1872,
        "combination": "Normal",
        "exerciseName": "SUPINE BENT KNEES YOGA",
        "displayName": "SUPINE BENT KNEES",
        "groupId": "703cff27c80d4c08b71dbddea17a6d1a",
        "concatName": "",
        "groupShow": 1,
        "exerciseType": "Yoga",
        "exerciseSubType": "",
        "description": "Lying on a mat with your knees bent and feet flat on the floor. \n\nBreath deep and settle the spine on the floor to quickly bring the breathing back to normal.",
        "videoLinkUrl": "https://youtu.be/VfSlEgg4ApE?t=1447",
        "animationId": 1872,
        "soundId": 1872,
        "bodyPart": "Lower body",
        "target": "Arm",
        "position": "Lying",
        "focus": "Relaxation",
        "equipment": "Yoga mat",
        "met": 3,
        "star": 1,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Cool Down",
        "intensity": "level 1",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1871,
        "combination": "Normal",
        "exerciseName": "STAFF BENT KNEES YOGA",
        "displayName": "STAFF BENT KNEES",
        "groupId": "1c4db3154a74476ab612b540f9e8ba6a",
        "concatName": "",
        "groupShow": 1,
        "exerciseType": "Yoga",
        "exerciseSubType": "Ashtanga",
        "description": "Distribute your weight between three points. \n\nFeet flat to the floor, bend in the knees, hands beside your hips.",
        "videoLinkUrl": "https://youtu.be/sXz0OCjO3p4?t=250",
        "animationId": 1871,
        "soundId": 1871,
        "bodyPart": "Upper body",
        "target": "Abs",
        "position": "Seated",
        "focus": "Relaxation",
        "equipment": "Resistance band,Yoga mat",
        "met": 3,
        "star": 1,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Cool Down",
        "intensity": "level 1",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1870,
        "combination": "Left & Right",
        "exerciseName": "123456",
        "displayName": "low hunge123--bed",
        "groupId": "691e4ffed881478ca3c25b6caddbe8b2",
        "concatName": "(Left)",
        "groupShow": 1,
        "exerciseType": "Yoga",
        "exerciseSubType": "Ashtanga,Hatha,Pilates,Vinyasa",
        "description": "我是一颗小小的石头，深深的埋在泥土之中",
        "videoLinkUrl": "https://youtu.be/O4xzzKdZy4Q?t=395",
        "animationId": 1870,
        "soundId": 1870,
        "bodyPart": "Lower body",
        "target": "Thigh,Butt,Leg,Hip,Hamstring",
        "position": "Prone",
        "focus": "Flexibility",
        "equipment": "Bed",
        "met": 3,
        "star": 2,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Main",
        "intensity": "level 1",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1869,
        "combination": "Left & Right",
        "exerciseName": "123456",
        "displayName": "low hunge123--bed",
        "groupId": "691e4ffed881478ca3c25b6caddbe8b2",
        "concatName": "(Right)",
        "groupShow": 0,
        "exerciseType": "Yoga",
        "exerciseSubType": "Ashtanga,Hatha,Pilates,Vinyasa",
        "description": "我是一颗小小的石头，深深的埋在泥土之中",
        "videoLinkUrl": "https://youtu.be/O4xzzKdZy4Q?t=395",
        "animationId": 1869,
        "soundId": 1869,
        "bodyPart": "Lower body",
        "target": "Thigh,Butt,Leg,Hip,Hamstring",
        "position": "Prone",
        "focus": "Flexibility",
        "equipment": "Bed",
        "met": 3,
        "star": 2,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Main",
        "intensity": "level 1",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1868,
        "combination": "Left & Right",
        "exerciseName": "奥力给就看到家里发大水654",
        "displayName": "HIGH LUNGE123456--chair",
        "groupId": "cda85a67b03e41af8b2ebd774a84fe4f",
        "concatName": "(Left)",
        "groupShow": 1,
        "exerciseType": "Yoga",
        "exerciseSubType": "Hatha,Pilates,Restorative",
        "description": "11111111111",
        "videoLinkUrl": "https://youtu.be/O4xzzKdZy4Q?t=409",
        "animationId": 1868,
        "soundId": 1868,
        "bodyPart": "Total body",
        "target": "Thigh,Butt,Leg,Back,Shoulder,Chest,Arm,Hip,Spine,Lower back",
        "position": "Standing",
        "focus": "Flexibility",
        "equipment": "Chair",
        "met": 3,
        "star": 2,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Main",
        "intensity": "level 1",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1872,
        "combination": "Normal",
        "exerciseName": "SUPINE BENT KNEES YOGA",
        "displayName": "SUPINE BENT KNEES",
        "groupId": "703cff27c80d4c08b71dbddea17a6d1a",
        "concatName": "",
        "groupShow": 1,
        "exerciseType": "Yoga",
        "exerciseSubType": "",
        "description": "Lying on a mat with your knees bent and feet flat on the floor. \n\nBreath deep and settle the spine on the floor to quickly bring the breathing back to normal.",
        "videoLinkUrl": "https://youtu.be/VfSlEgg4ApE?t=1447",
        "animationId": 1872,
        "soundId": 1872,
        "bodyPart": "Lower body",
        "target": "Arm",
        "position": "Lying",
        "focus": "Relaxation",
        "equipment": "Yoga mat",
        "met": 3,
        "star": 1,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Cool Down",
        "intensity": "level 1",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1871,
        "combination": "Normal",
        "exerciseName": "STAFF BENT KNEES YOGA",
        "displayName": "STAFF BENT KNEES",
        "groupId": "1c4db3154a74476ab612b540f9e8ba6a",
        "concatName": "",
        "groupShow": 1,
        "exerciseType": "Yoga",
        "exerciseSubType": "Ashtanga",
        "description": "Distribute your weight between three points. \n\nFeet flat to the floor, bend in the knees, hands beside your hips.",
        "videoLinkUrl": "https://youtu.be/sXz0OCjO3p4?t=250",
        "animationId": 1871,
        "soundId": 1871,
        "bodyPart": "Upper body",
        "target": "Abs",
        "position": "Seated",
        "focus": "Relaxation",
        "equipment": "Resistance band,Yoga mat",
        "met": 3,
        "star": 1,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Cool Down",
        "intensity": "level 1",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1870,
        "combination": "Left & Right",
        "exerciseName": "123456",
        "displayName": "low hunge123--bed",
        "groupId": "691e4ffed881478ca3c25b6caddbe8b2",
        "concatName": "(Left)",
        "groupShow": 1,
        "exerciseType": "Yoga",
        "exerciseSubType": "Ashtanga,Hatha,Pilates,Vinyasa",
        "description": "我是一颗小小的石头，深深的埋在泥土之中",
        "videoLinkUrl": "https://youtu.be/O4xzzKdZy4Q?t=395",
        "animationId": 1870,
        "soundId": 1870,
        "bodyPart": "Lower body",
        "target": "Thigh,Butt,Leg,Hip,Hamstring",
        "position": "Prone",
        "focus": "Flexibility",
        "equipment": "Bed",
        "met": 3,
        "star": 2,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Main",
        "intensity": "level 1",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1869,
        "combination": "Left & Right",
        "exerciseName": "123456",
        "displayName": "low hunge123--bed",
        "groupId": "691e4ffed881478ca3c25b6caddbe8b2",
        "concatName": "(Right)",
        "groupShow": 0,
        "exerciseType": "Yoga",
        "exerciseSubType": "Ashtanga,Hatha,Pilates,Vinyasa",
        "description": "我是一颗小小的石头，深深的埋在泥土之中",
        "videoLinkUrl": "https://youtu.be/O4xzzKdZy4Q?t=395",
        "animationId": 1869,
        "soundId": 1869,
        "bodyPart": "Lower body",
        "target": "Thigh,Butt,Leg,Hip,Hamstring",
        "position": "Prone",
        "focus": "Flexibility",
        "equipment": "Bed",
        "met": 3,
        "star": 2,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Main",
        "intensity": "level 1",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    },
    {
        "id": 1868,
        "combination": "Left & Right",
        "exerciseName": "奥力给就看到家里发大水654",
        "displayName": "HIGH LUNGE123456--chair",
        "groupId": "cda85a67b03e41af8b2ebd774a84fe4f",
        "concatName": "(Left)",
        "groupShow": 1,
        "exerciseType": "Yoga",
        "exerciseSubType": "Hatha,Pilates,Restorative",
        "description": "11111111111",
        "videoLinkUrl": "https://youtu.be/O4xzzKdZy4Q?t=409",
        "animationId": 1868,
        "soundId": 1868,
        "bodyPart": "Total body",
        "target": "Thigh,Butt,Leg,Back,Shoulder,Chest,Arm,Hip,Spine,Lower back",
        "position": "Standing",
        "focus": "Flexibility",
        "equipment": "Chair",
        "met": 3,
        "star": 2,
        "specialNeed": "",
        "remark": "",
        "status": 'Enabled',
        "createTime": "2022-11-08 13:33:26",
        "animationPhoneUrl": "https://hhcontent.s3.eu-central-1.amazonaws.com/t/63eb70af702b9300128171bb/u/63eb7057702b93001281719d/e/66903b25f042440012b67170/poster_a_720p.jpg",
        "difficulty": "Beginner",
        "functionType": "Main",
        "intensity": "level 1",
        "duration": Math.floor(Math.random() * 51) + 10 // 随机 10-60
    }
];

export const BATCH_FILE_OPTIONS = [
    { label: 'Video-M3U8 (生成M3U8视频文件)', value: 'Video-M3U8' },
    { label: 'Audio-JSON (生成JSON音频文件)', value: 'Audio-JSON' },
];

// Mock language options (replace with actual API call later)
export const MOCK_LANG_OPTIONS = [
    { label: 'EN', value: 'EN' },
    { label: 'ES', value: 'ES' },
    { label: 'FR', value: 'FR' },
    { label: 'DE', value: 'DE' },
]; 